import re
import os
from typing import List

# Paths
MODELS_DIR = "mahabharata/backend/app/models"
OUTPUT_FILE = "mahabharata/frontend/src/types/schema.ts"

# Simple mapping of Python types to TypeScript types
TYPE_MAP = {
    "str": "string",
    "int": "number",
    "float": "number",
    "bool": "boolean",
    "Any": "any",
    "Dict[str, Any]": "{ [key: string]: any }",
    "Dict": "{ [key: string]: any }",
    "List[str]": "string[]",
    "List[int]": "number[]",
    "List": "any[]",
    "Optional[str]": "string | null",
    "Optional[int]": "number | null",
    "datetime": "string", # Dates are usually ISO strings in JSON
}

def python_type_to_ts(py_type: str) -> str:
    # Handle List[Type]
    list_match = re.match(r"List\[(\w+)\]", py_type)
    if list_match:
        inner = list_match.group(1)
        return f"{python_type_to_ts(inner)}[]"
    
    # Handle Optional[Type]
    opt_match = re.match(r"Optional\[(\w+)\]", py_type)
    if opt_match:
        inner = opt_match.group(1)
        return f"{python_type_to_ts(inner)} | null"

    return TYPE_MAP.get(py_type, py_type)

def parse_pydantic_file(content: str) -> List[str]:
    ts_interfaces = []
    # Find classes inheriting from BaseModel
    classes = re.findall(r"class (\w+)\(BaseModel\):([\s\S]+?)(?=\nclass|\Z)", content)
    
    for class_name, class_body in classes:
        interface = f"export interface {class_name} {{\n"
        # Find fields like: name: type = default
        fields = re.findall(r"    (\w+): ([\w\[\], ]+)(?: = .+)?", class_body)
        for field_name, field_type in fields:
            ts_type = python_type_to_ts(field_type.strip())
            interface += f"  {field_name}: {ts_type};\n"
        interface += "}\n"
        ts_interfaces.append(interface)
    
    return ts_interfaces

def parse_dataclass_file(content: str) -> List[str]:
    ts_interfaces = []
    # Find classes with @dataclass
    classes = re.findall(r"@dataclass\nclass (\w+):([\s\S]+?)(?=\n@dataclass|\Z)", content)
    
    for class_name, class_body in classes:
        interface = f"export interface {class_name} {{\n"
        # Find fields like: name: type
        fields = re.findall(r"    (\w+): ([\w\[\], ]+)(?: = .+)?", class_body)
        for field_name, field_type in fields:
            ts_type = python_type_to_ts(field_type.strip())
            interface += f"  {field_name}: {ts_type};\n"
        interface += "}\n"
        ts_interfaces.append(interface)
    
    return ts_interfaces

def generate():
    all_ts = ["// Auto-generated by generate_types.py\n\n"]
    
    # Process domain.py (Pydantic)
    domain_path = os.path.join(MODELS_DIR, "domain.py")
    if os.path.exists(domain_path):
        with open(domain_path, "r") as f:
            all_ts.extend(parse_pydantic_file(f.read()))

    # Process orchestration.py (Dataclasses)
    orch_path = os.path.join(MODELS_DIR, "orchestration.py")
    if os.path.exists(orch_path):
        with open(orch_path, "r") as f:
            all_ts.extend(parse_dataclass_file(f.read()))

    # Ensure output directory exists
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    
    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(all_ts))
    
    print(f"✅ Successfully exported types to {OUTPUT_FILE}")

if __name__ == "__main__":
    generate()
