// Auto-generated by generate_types.py


export interface User {
  id: string;
  name: string;
  role: string;
  preferences: { [key: string]: any };
  active_project_id: string | null;
  created_at: string;
}

export interface Project {
  id: string;
  code: string;
  name: string;
  status: string;
  project_type: string;
  primary_owner: string;
  supporting_departments: string[];
  goal: string;
  review_frequency: string;
  created_at: string;
}

export interface Task {
  id: string;
  project_id: string | null;
  title: string;
  original_prompt: string;
  created_by: string;
  assigned_to: string | null;
  priority: string;
  risk_level: string;
  status: string;
  deadline: string | null;
  context: { [key: string]: any };
  created_at: string;
}

export interface DelegationNode {
  id: string;
  task_id: string;
  sender: string;
  receiver: string;
  message: string;
  reason: string;
  expected_output: string;
  status: string;
  editable: boolean;
  created_at: string;
}

export interface Output {
  id: string;
  task_id: string;
  agent_id: string;
  output_type: string;
  content: string;
  version: number;
  status: string;
  created_at: string;
}

export interface Interpretation {
  raw_prompt: string;
  objective: string;
  user_intent: string;
  assumptions: string[];
  clarifying_questions: string[];
}

export interface Classification {
  task_type: string;
  primary_department: string;
  output_format: string;
  project_context: string;
}

export interface StrategicAssessment {
  strategic_fit: string;
  urgency: string;
  importance: string;
  complexity: string;
  estimated_effort_minutes: number;
  reason: string;
}

export interface ReviewPolicy {
  qa_required: boolean;
  legal_required: boolean;
  citation_required: boolean;
  human_review_required: boolean;
  reasons: string[];
}

export interface HumanIntervention {
  required: boolean;
  reason: string | null;
}

export interface ContextPacket {
  id: string;
  task_id: string;
  original_prompt: string;
  original_intent: string;
  project_context: string;
  founder_preferences: { [key: string]: any };
  constraints: { [key: string]: any };
  created_at: string;
}

export interface ExecutionStep {
  id: string;
  department: string;
  objective: string;
  reason: string;
  expected_input: string;
  expected_output: string;
  output_schema: { [key: string]: any };
  depends_on: string[];
  can_run_parallel: boolean;
  estimated_time_minutes: number;
  model_choice: string | null;
  confidence_score: number;
}

export interface CEOEngineResult {
  task_id: string;
  interpretation: Interpretation;
  classification: Classification;
  strategic_assessment: StrategicAssessment;
  decision: DecisionType;
  priority: PriorityLevel;
  risk_level: RiskLevel;
  execution_mode: ExecutionMode;
  route: string[];
  success_criteria: string[];
  context_packet: ContextPacket;
  delegation_plan: ExecutionStep[];
  review_policy: ReviewPolicy;
  human_intervention: HumanIntervention;
  ceo_reasoning: string;
  confidence_score: number;
}

export interface DelegationNode {
  id: string;
  task_id: string;
  context_packet_id: string;
  sender: string;
  receiver: string;
  message: string;
  reason: string;
  expected_input: string;
  expected_output: string;
  output_schema: { [key: string]: any };
  dependency_ids: string[];
  status: NodeStatus;
  editable: boolean;
  estimated_time_minutes: number;
  model_choice: string | null;
  confidence_score: number;
  created_at: string;
}
